# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f5f9b0a0ffa52a0e4a7ef09be5e98437021a0469848b26f0f6bc3b790cd19794f44591f30891193309c5dfe807e97b8ad3f2f2df3081c84428ac5787b442d5d

test:
  secret_key_base: c6d888bb69dcd1fc01d59116a754ad089b9acc85041e781db68a8b36b0d77d8f81da89caa0084b192663805343991672717b56551f57b82f4a30567ea3aafd62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
